/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Administrator
 */
public class daftar extends javax.swing.JFrame {

    /**
     * Creates new form daftar
     */
    public daftar() {
        initComponents();
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        laki = new javax.swing.JRadioButton();
        wanita = new javax.swing.JRadioButton();
        nomor = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        agama = new javax.swing.JComboBox<>();
        daftar = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DAFTAR");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(583, 390));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("username :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 80, 70, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("password :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 110, 80, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("nama lengkap :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 140, 90, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("alamat :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 170, 50, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("nomor telepon :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 270, 100, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("jenis kelamin :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 240, 90, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("email :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 300, 50, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("agama :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 330, 50, 20);
        jPanel1.add(username);
        username.setBounds(110, 80, 200, 20);
        jPanel1.add(nama);
        nama.setBounds(130, 140, 180, 20);
        jPanel1.add(password);
        password.setBounds(110, 110, 200, 20);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 170, 220, 60);

        jeniskelamin.add(laki);
        laki.setSelected(true);
        laki.setText("laki-laki");
        jPanel1.add(laki);
        laki.setBounds(130, 240, 59, 23);

        jeniskelamin.add(wanita);
        wanita.setText("wanita");
        jPanel1.add(wanita);
        wanita.setBounds(250, 240, 57, 23);
        jPanel1.add(nomor);
        nomor.setBounds(140, 270, 170, 20);
        jPanel1.add(email);
        email.setBounds(90, 300, 220, 20);

        agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Hindu", "Budha", "Kristen", "Khatolik", "KongHucu" }));
        jPanel1.add(agama);
        agama.setBounds(90, 330, 220, 20);

        daftar.setText("DAFTAR");
        jPanel1.add(daftar);
        daftar.setBounds(230, 23, 90, 30);

        exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back1.png"))); // NOI18N
        exit.setText("kembali");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(exit);
        exit.setBounds(10, 10, 150, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/backgroundmain.jpg"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(583, 390));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 350, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agama;
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton daftar;
    private javax.swing.JTextField email;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nomor;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    private javax.swing.JRadioButton wanita;
    // End of variables declaration//GEN-END:variables

    public void addlistener(ActionListener e){
        daftar.addActionListener(e);
    }
    
    public void addmouseistener(MouseListener e){
        exit.addMouseListener(e);
    }
    
    public String getusername(){
        return username.getText();
    }
    
    public String getpassword(){
        return String.valueOf(password.getText());
    }
    
    public String getnama(){
        return nama.getText();
    }
    
    public String getalamat(){
        return alamat.getText();
    }
    
    public String getnomor(){
        return nomor.getText();
    }
    
    public char getkelamin(){
        if (laki.isSelected()) return 'L';
        else return 'P';
    }
    
    public String getemail(){
        return email.getText();
    }
    
    public String getagama(){
        return String.valueOf(agama.getSelectedItem());
    }
    
    public Object getexit(){
        return exit;
    }
}
