/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main(String x) {
        initComponents();
        user.setText(x);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
    }

    public JLabel getExit() {
        return exit;
    }

    public JLabel getHapus() {
        return hapus;
    }

    public JLabel getLihat() {
        return lihat;
    }

    public JLabel getPrediksi() {
        return prediksi;
    }

    public JLabel getTambah() {
        return tambah;
    }

    public JLabel getTambahuser() {
        return tambahuser;
    }
    public void addlistener(MouseListener e){
        exit.addMouseListener(e);
        tambahuser.addMouseListener(e);
        tambah.addMouseListener(e);
        hapus.addMouseListener(e);
        prediksi.addMouseListener(e);
        lihat.addMouseListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lihat = new javax.swing.JLabel();
        tambah = new javax.swing.JLabel();
        tambahuser = new javax.swing.JLabel();
        hapus = new javax.swing.JLabel();
        prediksi = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(583, 450));
        jPanel1.setLayout(null);

        lihat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lihat.setForeground(new java.awt.Color(255, 255, 0));
        lihat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pesanan.png"))); // NOI18N
        lihat.setText("PESAN SEKARANG");
        lihat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lihat);
        lihat.setBounds(179, 127, 290, 45);

        tambah.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 0));
        tambah.setIcon(new javax.swing.ImageIcon("E:\\tubes\\src\\gambar\\menu.png")); // NOI18N
        tambah.setText("LIHAT PESANAN");
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(tambah);
        tambah.setBounds(179, 178, 270, 45);

        tambahuser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tambahuser.setForeground(new java.awt.Color(255, 255, 0));
        tambahuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pesan.png"))); // NOI18N
        tambahuser.setText("LIHAT MENU");
        tambahuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(tambahuser);
        tambahuser.setBounds(179, 72, 209, 50);

        hapus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 0));
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mesage.png"))); // NOI18N
        hapus.setText("KIRIM PESAN KE ADMIN");
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(hapus);
        hapus.setBounds(179, 229, 370, 45);

        prediksi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        prediksi.setForeground(new java.awt.Color(51, 204, 0));
        prediksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/prediksi.png"))); // NOI18N
        prediksi.setText("PREDIKSI");
        prediksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(prediksi);
        prediksi.setBounds(179, 280, 176, 50);

        user.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        user.setForeground(new java.awt.Color(51, 204, 0));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon.png"))); // NOI18N
        jPanel1.add(user);
        user.setBounds(10, 13, 213, 48);

        exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 204, 0));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N
        exit.setText("EXIT");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(exit);
        exit.setBounds(446, 13, 112, 35);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/backgroundmain.jpg"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(583, 390));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 583, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel hapus;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lihat;
    private javax.swing.JLabel prediksi;
    private javax.swing.JLabel tambah;
    private javax.swing.JLabel tambahuser;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
